USE open_bbs;

ALTER TABLE fs_comment
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN pre_id BIGINT NULL DEFAULT 0;

ALTER TABLE fs_like
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE fs_comment_like
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN comment_id BIGINT NOT NULL;

ALTER TABLE fs_dynamic
    MODIFY COLUMN comment_id BIGINT NULL;

