server {
    listen 80;
    server_name localhost;

    location /static/articles/ {
        alias D:/D/大学学习/大三下/分布式/大作业/Blog/bbs-springboot/bbs-article/bbs-article-service/article-static-html/;
        add_header Cache-Control "public, max-age=300";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:7010/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
